### ISSUE TITLE
Sweep: i want to add the slug data of projects in the api response

### ISSUE THREAD

**Issue by labi1240** [labi1240/projectsAPI#1]
Here is the sample of Data

for the url http://127.0.0.1:8000/projects/prince-george-landing. What i want is to add the "slug": "prince-george-landing", inside you can write it as project name just have to add the - - in projects

 "_id": "842d135f-4c3a-46ad-952c-73d87ad538a3",
        "name": "Prince George Landing",
        "status": "Pending",
        "price": "Not available",
        "incentives": "Not available",
        "address": "17 Baldwin Street,",
        "developer": "Stockworth Developments",
        "buildingType": "Condo & Townhouse",
        "unitsStories": "85 Units,",
        "bedrooms": "1 - 3 Bedrooms",
        "sizeSqFt": "Not available",
        "estimatedCompletion": "Preconstruction",

<details open>
<summary>Checklist</summary>

- [X] Modify `models.py` ✓ https://github.com/labi1240/projectsAPI/commit/3b5c3e855c64e4d5939ac0f6cc6c95643c5a5f7a [Edit](https://github.com/labi1240/projectsAPI/edit/sweep/i_want_to_add_the_slug_data_of_projects/models.py)
- [X] Running GitHub Actions for `models.py` ✓  [Edit](https://github.com/labi1240/projectsAPI/edit/sweep/i_want_to_add_the_slug_data_of_projects/models.py)
- [X] Modify `mongodb_utils.py` ✓ https://github.com/labi1240/projectsAPI/commit/b734b2c6f6d9d8e031b2382f2595bc5c892e0a76 [Edit](https://github.com/labi1240/projectsAPI/edit/sweep/i_want_to_add_the_slug_data_of_projects/mongodb_utils.py)
- [X] Running GitHub Actions for `mongodb_utils.py` ✓  [Edit](https://github.com/labi1240/projectsAPI/edit/sweep/i_want_to_add_the_slug_data_of_projects/mongodb_utils.py)
- [X] Modify `main.py` ! No changes made  [Edit](https://github.com/labi1240/projectsAPI/edit/sweep/i_want_to_add_the_slug_data_of_projects/main.py)
- [X] Running GitHub Actions for `main.py` ✗  [Edit](https://github.com/labi1240/projectsAPI/edit/sweep/i_want_to_add_the_slug_data_of_projects/main.py)
</details>

**Comment by labi1240** [comment]
<div align='center'><a href="https://github.com/sweepai/sweep"><img class="swing" src="https://raw.githubusercontent.com/sweepai/sweep/main/.assets/sweeping.gif" width="100" style="width:50px; margin-bottom:10px" alt="Sweeping"></a></div><br/><div align='center'>

<img src='https://progress-bar.dev/0/?&title=Errored&width=600' alt='0%' /></div>



---
## Actions (click)
- [ ] ↻ Restart Sweep

---
## ❌ Unable to Complete PR
It looks like an issue has occurred around fetching the files. Perhaps the repo failed to initialized. If this error persists contact team@sweep.dev.

> @labi1240, editing this issue description to include more details will automatically make me relaunch. Please join our Discord server for support (tracking_id=a6c7f55f05)

For bonus GPT-4 tickets, please report this bug on **[Discord](https://discord.gg/invite/sweep)** (tracking ID: `a6c7f55f05`).

---

<details>
<summary><b>🎉 Latest improvements to Sweep:</b></summary>
<ul>
<li>New <a href="https://progress.sweep.dev">dashboard</a> launched for real-time tracking of Sweep issues, covering all stages from search to coding.</li>
<li>Integration of OpenAI's latest Assistant API for more efficient and reliable code planning and editing, improving speed by 3x.</li>
<li>Use the <a href="https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github">GitHub issues extension</a> for creating Sweep issues directly from your editor.</li>
</ul>
</details>


💡 To recreate the pull request edit the issue title or description.

*This is an automated message generated by [Sweep AI](https://sweep.dev).*

**Comment by labi1240** [comment]
❯ uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['/Users/lovepreetgill/developer/[001]_API/FastAPI']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [74222] using StatReload
/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
INFO:     Started server process [74224]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:53612 - "GET /projects HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/fastapi/routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 6 validation errors:
  {'type': 'string_type', 'loc': ('response', 34, 'images', 6, 'ImageName'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}
  {'type': 'string_type', 'loc': ('response', 69, 'images', 0, 'ImageName'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}
  {'type': 'string_type', 'loc': ('response', 69, 'images', 1, 'ImageName'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}
  {'type': 'string_type', 'loc': ('response', 83, 'images', 0, 'ImageName'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}
  {'type': 'string_type', 'loc': ('response', 96, 'images', 1, 'ImageName'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}
  {'type': 'string_type', 'loc': ('response', 126, 'images', 0, 'ImageName'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}

**Comment by labi1240** [comment]
❯ uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['/Users/lovepreetgill/developer/[001]_API/FastAPI']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [74222] using StatReload
/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
INFO:     Started server process [74224]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:53612 - "GET /projects HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lovepreetgill/developer/[001]_API/FastAPI/newenv/lib/python3.11/site-packages/fastapi/routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 6 validation errors:
  {'type': 'string_type', 'loc': ('response', 34, 'images', 6, 'ImageName'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}
  {'type': 'string_type', 'loc': ('response', 69, 'images', 0, 'ImageName'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}
  {'type': 'string_type', 'loc': ('response', 69, 'images', 1, 'ImageName'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}
  {'type': 'string_type', 'loc': ('response', 83, 'images', 0, 'ImageName'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}
  {'type': 'string_type', 'loc': ('response', 96, 'images', 1, 'ImageName'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}
  {'type': 'string_type', 'loc': ('response', 126, 'images', 0, 'ImageName'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}
